export const analysisLabels: Record<string,string> = {
  "profile": "组库指标与分组比较",
  "boxplot": "分组箱线图",
  "pep-analysis": "克隆共享分析",
  "topclone": "优势克隆分析",
  "db-alignment": "数据库比对",
  "pgen-analysis": "生成概率分析",
  "umap": "样本降维",
  "umapin": "特征降维",
  "volcano": "差异分析",
  "go-kegg-enrichment": "基因功能与通路富集",
  "ml-analysis": "机器学习",
  "mait-nkt": "特征细胞分析",
  "charts": "组库图表",
  "charts.combined": "组库图表",
  "treemap.generate": "克隆分布树图",
  "chord.generate": "基因配对弦图",
  "statistical.analyze": "统计分析",
  "statistical.boxplot": "统计箱线图",
  "statistical.analyze-multiple": "多指标统计",
  "statistical.summary-boxplot": "汇总箱线图",
  "statistical.analyze-batch": "批量统计",
  "statistical.analyze-direct": "直接统计",
  "auto-heatmap.generate-heatmap": "组库热力图",
  "auto-heatmap.generate-pipeline-report": "分析流程报告",
  "auto-heatmap.generate-heatmap-report": "热力图报告",
  "auto-heatmap.export-shared-cdr3": "共享克隆序列导出",
  "ppt.scan-images": "扫描报告图片",
  "ppt.load-image": "读取报告图片",
  "ppt.render-slides": "生成演示文稿",
  "ppt-comparison.scan-heatmaps": "扫描比较热力图",
  "ppt-comparison.generate": "生成比较报告",
  "analysis.execute": "数据分析",
  "analysis.batch": "批量数据分析",
  "analysis.execute-unified": "指标方案分析",
  "script-hub": "组合分析"
};
export const analysisLabel = (key?: string | null) => key ? analysisLabels[key] || (/[\u4e00-\u9fff]/.test(key) ? key : "其他分析") : "分析结果";
