import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { MemoryRouter } from "react-router-dom";
import { ProjectGroupSpecs } from "../features/projects/ProjectGroupSpecs";
import * as projects from "../shared/api/projects";
import { apiClient } from "../shared/api/client";
import type { ProjectAsset } from "../shared/types/domain";
const asset=(id:string):ProjectAsset=>({id,project_id:"p",asset_type:"profile",original_name:id+".csv",storage_path:"/synthetic/"+id,size:1,metadata:{asset_set:"甲",content_version:"v-"+id}});
const schema={columns:["sample","group"],sheets:[],requires_sheet_selection:false,selected_sheet:null};
const values={values:["A","B"],row_counts:{A:1,B:1},sample_counts:{A:1,B:1},samples_by_value:{},sample_column:"sample",content_version:"v-page2",asset_set:"甲"};
afterEach(()=>{cleanup();vi.restoreAllMocks();apiClient.invalidateCache();});
it("来源分页与搜索不丢页外选择，也不下载全部完整候选",async()=>{
  const list=vi.spyOn(projects,"listProjectAssets").mockImplementation(async(_id,options)=>({assets:options?.search?[]:[asset(options?.page===2?"page2":"page1")],pagination:{page:options?.page || 1,page_size:20,total:options?.search?0:21,total_pages:options?.search?0:2}}));
  const get=vi.spyOn(projects,"getProjectAsset").mockResolvedValue({asset:asset("page2")});
  vi.spyOn(apiClient,"post").mockResolvedValue(schema);vi.spyOn(apiClient,"get").mockResolvedValue(values);
  render(<MemoryRouter initialEntries={["/?asset_set=甲"]}><ProjectGroupSpecs projectId="p" loading={false} groupSpecs={[]} onChanged={vi.fn()}/></MemoryRouter>);
  fireEvent.click(await screen.findByRole("button",{name:"指标表下一页"}));
  await waitFor(()=>expect(list).toHaveBeenLastCalledWith("p",expect.objectContaining({view:"selector",page:2,pageSize:20,assetSet:"甲",assetType:"profile"})));
  fireEvent.click(screen.getByRole("button",{name:"方案来源指标表"}));fireEvent.click(await screen.findByRole("option",{name:/page2.csv/}));
  await screen.findByRole("button",{name:"方案分组字段"});
  fireEvent.click(screen.getByRole("button",{name:"指标表上一页"}));
  await screen.findByText("已选来源保留在当前候选页之外：page2.csv");
  fireEvent.change(screen.getByRole("textbox",{name:"搜索指标表名称"}),{target:{value:"不存在"}});
  fireEvent.click(screen.getByRole("button",{name:"查询来源"}));
  await screen.findByText("没有符合名称的指标表，请调整搜索；已选来源仍保留。");
  expect(screen.getByRole("button",{name:"方案来源指标表"})).toHaveTextContent("page2.csv");
  expect(list.mock.calls.every(([,options])=>!options?.allPages)).toBe(true);expect(get).not.toHaveBeenCalled();
});
it("编辑历史来源不在候选页时按轻量身份恢复，失败可重试",async()=>{
  vi.spyOn(projects,"listProjectAssets").mockResolvedValue({assets:[asset("new")],pagination:{page:1,page_size:20,total:1,total_pages:1}});
  const get=vi.spyOn(projects,"getProjectAsset").mockRejectedValueOnce(new Error("旧版断连")).mockResolvedValue({asset:{...asset("old"),metadata:{...asset("old").metadata,superseded:true}}});
  const post=vi.spyOn(apiClient,"post").mockImplementation(async(url)=>url.endsWith("/input-schema")?schema:{} as never);
  vi.spyOn(apiClient,"get").mockResolvedValue({...values,content_version:"v-old"});
  const scheme={id:"s",name:"旧版方案",spec_json:{source_asset_id:"old",source_content_version:"v-old",asset_set:"甲",group_field:"group",groups:["B","A"]}};
  render(<MemoryRouter initialEntries={["/?asset_set=甲"]}><ProjectGroupSpecs projectId="p" loading={false} groupSpecs={[scheme]} onChanged={vi.fn()}/></MemoryRouter>);
  fireEvent.click(screen.getByRole("button",{name:"编辑"}));
  await screen.findByText("旧版断连");expect(screen.getByRole("button",{name:"保存"})).toBeDisabled();
  expect(get).toHaveBeenCalledWith("p","old",{view:"selector"});
  fireEvent.click(screen.getByRole("button",{name:"重新读取当前指标"}));
  await waitFor(()=>expect(screen.getByRole("button",{name:"保存"})).toBeEnabled());
  expect(screen.getByRole("button",{name:"方案来源指标表"})).toHaveTextContent("历史版本");
  fireEvent.click(screen.getByRole("button",{name:"保存"}));
  await waitFor(()=>expect(post).toHaveBeenCalledWith("/api/projects/p/group-specs",expect.objectContaining({id:"s",spec_json:expect.objectContaining({source_asset_id:"old",source_content_version:"v-old",groups:["B","A"]})})));
  expect(projects.listProjectAssets).toHaveBeenCalledWith("p",expect.objectContaining({includeSuperseded:true}));
});
