# Generated by Django 4.2 on 2024-10-08 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appone", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="password",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(verbose_name="年龄"),
        ),
    ]
